function init(self)
end

function on_message(self, message_id, message, sender)
-- keyboard test
	if message_id == hash("spacebar") then
			label.set_text("#PressSpace", "spacebar pressed")
	end

	if message_id == hash("help") then
			label.set_text("#PressSpace", "h pressed")
	end
	
-- mouse test
	if message_id == hash("left") then
			label.set_text("#PressSpace", "left mouse clicked")
	end

	if message_id == hash("right") then
			label.set_text("#PressSpace", "right mouse clicked")
	end
end